# Generated by Django 4.1.2 on 2023-01-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='club_name',
            new_name='club',
        ),
    ]
