# Generated by Django 4.1.2 on 2023-01-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=300)),
                ('lastName', models.CharField(max_length=100)),
                ('cardType', models.CharField(max_length=100)),
                ('cardNumber', models.CharField(max_length=100)),
                ('expiryDate', models.CharField(max_length=100)),
                ('names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.clubname')),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('credit card', 'Credit Card'), ('debit card', 'Debit Card')], default='green', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
