# Generated by Django 4.1.2 on 2023-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_clubrep_mymodel_delete_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='clubrep',
            name='names',
        ),
        migrations.AddField(
            model_name='clubrep',
            name='clubName',
            field=models.ManyToManyField(blank=True, null=True, to='hello.clubname'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
