# Generated by Django 4.1.2 on 2023-01-11 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0008_alter_clubrep_clubname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubname',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubName', to=settings.AUTH_USER_MODEL),
        ),
    ]
