# Generated by Django 4.1.2 on 2023-01-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_alter_clubname_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubrep',
            name='clubName',
        ),
        migrations.AddField(
            model_name='clubrep',
            name='clubName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.clubname'),
        ),
    ]
