# Generated by Django 4.1.2 on 2023-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_remove_clubrep_clubname_clubrep_clubname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrep',
            name='expiryDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='lastName',
            field=models.CharField(max_length=1),
        ),
    ]
