# Generated by Django 4.1.2 on 2023-01-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_alter_clubrep_cardnumber_alter_clubrep_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrep',
            name='cardNumber',
            field=models.CharField(max_length=19),
        ),
    ]
